/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unisal.aula.telas;
import br.unisal.aula.dal.ModuloConexao;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author mtheu
 */
public class TelaLogin extends javax.swing.JFrame {
    // Usando a variavel conexao do DAL
    Connection conexao = null;
    // criando variaveis especiais para conexão com o banco
    // PreparedStatement e ResultSet são frameworks do pacote java.sql
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public void logar(){
        String sql = "select *, true from tbusuarios where login = ? and senha = ?";
        try {
            /* As linhas abaixo preparam a consulta ao banco de dados em função do
            que foi digitado nas caixas de texto. O ? é substituido pelo conteudo 
            das variaveis.
            */
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtUsuario.getText());
            pst.setString(2, txtSenha.getText());
            // a linha abaixo executa a query (consulta do banco de dados)
            rs = pst.executeQuery();
            
            // se exebir usuário e senha correspondendo
            if (rs.next()) {
                // a linha abaixo obtem o conteúdo do campo perfil (admin / user) da tabela tbusuarios
                String perfil = rs.getString(6);
                // System.out.println(perfil);
                // a estrutura abaixo faz o tratamento do perfil do usuario
                if (perfil.equals("admin")) {
                    // a linha abaixo exibe o conteudo do campo da tabela
                    TelaPrincipal principal = new TelaPrincipal();
                    principal.setVisible(true);
                    TelaPrincipal.menCadUsu.setEnabled(true); // ativa o menu relatorio para quem é o administrador
                    TelaPrincipal.lblUsuario.setText(rs.getString(2));
                    TelaPrincipal.lblUsuario.setForeground(Color.red); 
                    this.dispose(); // fecha a tela de login depois de abrir a tela principal
                    conexao.close(); // fecha a conexão com o banco de dados
                } else {
                    TelaPrincipal principal = new TelaPrincipal();
                    principal.setVisible(true);
                    TelaPrincipal.lblUsuario.setText(rs.getString(2));
                    this.dispose();
                    conexao.close();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e / ou senha incoretos");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setSize(620,340); // tamanho da tela inicial
        getRootPane().setDefaultButton(btnLogin);
        
        // Conexão
        conexao = ModuloConexao.conector();
        // a linha abaixo serve de apoio ao status da conexão
        // se estiver conectado, estára verde e mostrara "conectado"
        // se não tiver conectado, estara vermelho e mostrada "desconectado"
        //System.out.println(conexao); 
        if (conexao != null){
            lblstatus.setText("Conectado");
            //jLabel1.setForeground(Color.red);
            lblstatus.setForeground(Color.green); 
        } else {
            lblstatus.setText("Desconectado");
            lblstatus.setForeground(Color.RED);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        txt_idenusuario = new javax.swing.JLabel();
        lb_imgclientes = new javax.swing.JLabel();
        lblstatus = new javax.swing.JLabel();
        lb_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto - Identificação do Usuario");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Usuario: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 90, 90, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 130, 70, 22);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(200, 90, 210, 30);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(200, 130, 210, 30);

        btnLogin.setText("Entrar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(240, 180, 90, 30);

        txt_idenusuario.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        txt_idenusuario.setText("Identificação do Usuário");
        getContentPane().add(txt_idenusuario);
        txt_idenusuario.setBounds(110, 30, 340, 50);

        lb_imgclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrado/img/clientes.png"))); // NOI18N
        getContentPane().add(lb_imgclientes);
        lb_imgclientes.setBounds(340, 120, 280, 210);

        lblstatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblstatus.setText("Status");
        getContentPane().add(lblstatus);
        lblstatus.setBounds(20, 260, 140, 30);

        lb_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrado/img/background1.jpg"))); // NOI18N
        getContentPane().add(lb_fundo);
        lb_fundo.setBounds(0, -15, 620, 340);

        setSize(new java.awt.Dimension(620, 340));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // chamar o método logar
        logar();
    }//GEN-LAST:event_btnLoginActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb_fundo;
    private javax.swing.JLabel lb_imgclientes;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel txt_idenusuario;
    // End of variables declaration//GEN-END:variables
}
